<?php

namespace ContainerUSJ9XAM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDtoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Model\UserDto' shared autowired service.
     *
     * @return \App\Model\UserDto
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Model\\UserDto": argument "$firstName" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
