<?php

namespace ContainerXxvbRSt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SpT6DHIService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.SpT6DHI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SpT6DHI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'logger' => ['privates', 'monolog.logger.request', 'getMonolog_Logger_RequestService', false],
            'projectDir' => ['privates', '.value.47DvH.H', 'get_Value_47DvH_HService', true],
        ], [
            'logger' => 'Psr\\Log\\LoggerInterface',
            'projectDir' => '?',
        ]);
    }
}
