<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Product__CLASSMETADATA__' => 0,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\SequenceGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\SequenceGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Product',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\ProductRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    2,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'reference' => $o[2],
                        'price' => $o[3],
                        'fabricationDate' => $o[4],
                        'brochureFilename' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'reference' => 'reference',
                        'price' => 'price',
                        'fabrication_date' => 'fabricationDate',
                        'brochure_filename' => 'brochureFilename',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'reference' => 'reference',
                        'price' => 'price',
                        'fabricationDate' => 'fabrication_date',
                        'brochureFilename' => 'brochure_filename',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'product',
                    ],
                ],
                'idGenerator' => [
                    $o[6],
                ],
                'sequenceGeneratorDefinition' => [
                    [
                        'sequenceName' => 'product_id_seq',
                        'allocationSize' => '1',
                        'initialValue' => '1',
                    ],
                ],
                'name' => [
                    'App\\Entity\\Product',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'date',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'reference',
                    'price',
                    'fabricationDate',
                    'brochureFilename',
                ],
                'columnName' => [
                    1 => 'id',
                    'reference',
                    'price',
                    'fabrication_date',
                    'brochure_filename',
                ],
                'length' => [
                    2 => 255,
                    255,
                ],
            ],
        ],
        $o[0],
        [
            -6 => [
                'allocationSize' => 1,
                'sequenceName' => 'product_id_seq',
            ],
        ]
    );
},

]];
