<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSet14Z9\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSet14Z9/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerSet14Z9.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerSet14Z9\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerSet14Z9\App_KernelProdContainer([
    'container.build_hash' => 'Set14Z9',
    'container.build_id' => 'e67708fc',
    'container.build_time' => 1762825582,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSet14Z9');
