<?php

namespace ContainerSet14Z9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Value_ZfJlKwdService extends App_KernelProdContainer
{
    /*
     * Gets the private '.value.zfJlKwd' shared service.
     *
     * @return \mixed
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.value.zfJlKwd'] = \dirname(__DIR__, 4);
    }
}
