<?php

namespace ContainerSet14Z9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0qVz9GLService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.0qVz9GL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0qVz9GL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'logger' => ['privates', 'monolog.logger.request', 'getMonolog_Logger_RequestService', false],
            'projectDir' => ['privates', '.value.zfJlKwd', 'get_Value_ZfJlKwdService', true],
        ], [
            'logger' => 'Psr\\Log\\LoggerInterface',
            'projectDir' => '?',
        ]);
    }
}
