<?php

namespace ContainerSet14Z9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\LuckyController::number' => ['privates', '.service_locator.Q9_Ua5J', 'get_ServiceLocator_Q9Ua5JService', true],
            'App\\Controller\\LuckyController::numberBis' => ['privates', '.service_locator.0qVz9GL', 'get_ServiceLocator_0qVz9GLService', true],
            'App\\Controller\\LuckyController::dashboardBis' => ['privates', '.service_locator.kv0OVG.', 'get_ServiceLocator_Kv0OVG_Service', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.LNwsF6h', 'get_ServiceLocator_LNwsF6hService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.TxLdxz8', 'get_ServiceLocator_TxLdxz8Service', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.N7dcDh9', 'get_ServiceLocator_N7dcDh9Service', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.N7dcDh9', 'get_ServiceLocator_N7dcDh9Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\LuckyController:number' => ['privates', '.service_locator.Q9_Ua5J', 'get_ServiceLocator_Q9Ua5JService', true],
            'App\\Controller\\LuckyController:numberBis' => ['privates', '.service_locator.0qVz9GL', 'get_ServiceLocator_0qVz9GLService', true],
            'App\\Controller\\LuckyController:dashboardBis' => ['privates', '.service_locator.kv0OVG.', 'get_ServiceLocator_Kv0OVG_Service', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.DZowHzb', 'get_ServiceLocator_DZowHzbService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.LNwsF6h', 'get_ServiceLocator_LNwsF6hService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.TxLdxz8', 'get_ServiceLocator_TxLdxz8Service', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.N7dcDh9', 'get_ServiceLocator_N7dcDh9Service', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.N7dcDh9', 'get_ServiceLocator_N7dcDh9Service', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\LuckyController::number' => '?',
            'App\\Controller\\LuckyController::numberBis' => '?',
            'App\\Controller\\LuckyController::dashboardBis' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\LuckyController:number' => '?',
            'App\\Controller\\LuckyController:numberBis' => '?',
            'App\\Controller\\LuckyController:dashboardBis' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:delete' => '?',
        ]));
    }
}
