<?php

namespace ContainerSet14Z9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSomeCommandService extends App_KernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.App\Command\SomeCommand' shared autowired service.
     *
     * @return \App\Command\SomeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.App\\Command\\SomeCommand'] = new \App\Command\SomeCommand(($container->services['router'] ?? self::getRouterService($container)));
    }
}
