<?php

namespace ContainerAhEZpVn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Value_47DvH_HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.value.47DvH.H' shared service.
     *
     * @return \mixed
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.value.47DvH.H'] = \dirname(__DIR__, 4);
    }
}
