<?php

namespace ContainerAhEZpVn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kv0OVG_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kv0OVG.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kv0OVG.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userDto' => ['privates', 'App\\Model\\UserDto', NULL, 'Cannot autowire service "App\\Model\\UserDto": argument "$firstName" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'userDto' => 'App\\Model\\UserDto',
        ]);
    }
}
