<?php

namespace ContainerAhEZpVn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSomeCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SomeCommand' shared autowired service.
     *
     * @return \App\Command\SomeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/SomeCommand.php';

        $container->privates['App\\Command\\SomeCommand'] = $instance = new \App\Command\SomeCommand(($container->services['router'] ?? self::getRouterService($container)));

        $instance->setName('app:some-command');
        $instance->setDescription('Do something cool');

        return $instance;
    }
}
