<?php

namespace ContainerAhEZpVn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSomeCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\SomeCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\SomeCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:some-command', [], 'Do something cool', false, #[\Closure(name: 'App\\Command\\SomeCommand')] fn (): \App\Command\SomeCommand => ($container->privates['App\\Command\\SomeCommand'] ?? $container->load('getSomeCommandService')));
    }
}
