<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJjWDBpw\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJjWDBpw/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJjWDBpw.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJjWDBpw\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerJjWDBpw\App_KernelTestDebugContainer([
    'container.build_hash' => 'JjWDBpw',
    'container.build_id' => '23755996',
    'container.build_time' => 1762832511,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJjWDBpw');
