<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUSJ9XAM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUSJ9XAM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUSJ9XAM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUSJ9XAM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUSJ9XAM\App_KernelDevDebugContainer([
    'container.build_hash' => 'USJ9XAM',
    'container.build_id' => '2c02a49b',
    'container.build_time' => 1762833640,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUSJ9XAM');
